version: '3'

services:
  php-cli:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: redis:7.4.1-alpine
    networks:
      - app-network
    ports:
      - "6379:6379"

networks:
  app-network:
    driver: bridge
